# -*- coding: utf-8 -*-
"""Predictive Rainwater Harvesting Optimization System (linear regressor rainfall prediction).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TDC6weC8wPELBP-Afb-BdoEx2yIMzmq9
"""

# Upload CSV file if running directly in Colab
from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Load dataset
df = pd.read_csv('pimpri_chinchwad_rainfall_2015_2024.csv')
df['Date'] = pd.to_datetime(df['Date'])

# Create cyclical features for seasonality (sine and cosine transforms)
df['DayOfYear'] = df['Date'].dt.dayofyear
df['Sin_Month'] = np.sin(2 * np.pi * df['Month'] / 12)
df['Cos_Month'] = np.cos(2 * np.pi * df['Month'] / 12)

# Create lag and rolling features
df['Rain_Lag1'] = df['Rainfall_mm'].shift(1).fillna(0)
df['Rain_Rolling7'] = df['Rainfall_mm'].rolling(window=7, min_periods=1).mean()

print(df.head())

# Define feature set and target
features = ['Temperature_C', 'Humidity_pct', 'Sin_Month', 'Cos_Month', 'Rain_Lag1', 'Rain_Rolling7']
target = 'Rainfall_mm'

X = df[features]
y = df[target]

# Chronological split: 2015-2022 for Training, 2023-2024 for Testing
train_idx = df['Year'] < 2023
test_idx = df['Year'] >= 2023

X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]

print(f"Training Samples: {len(X_train)} | Testing Samples: {len(X_test)}")

# Define feature set and target
features = ['Temperature_C', 'Humidity_pct', 'Sin_Month', 'Cos_Month', 'Rain_Lag1', 'Rain_Rolling7']
target = 'Rainfall_mm'

X = df[features]
y = df[target]

# Chronological split: 2015-2022 for Training, 2023-2024 for Testing
train_idx = df['Year'] < 2023
test_idx = df['Year'] >= 2023

X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]

print(f"Training Samples: {len(X_train)} | Testing Samples: {len(X_test)}")

# Initialize and train Linear Regression
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions (clip at 0 to avoid negative rainfall values)
y_pred_train = np.clip(model.predict(X_train), 0, None)
y_pred_test = np.clip(model.predict(X_test), 0, None)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
r2 = r2_score(y_test, y_pred_test)

print(f"Test MAE:  {mae:.3f} mm")
print(f"Test RMSE: {rmse:.3f} mm")
print(f"Test R²:   {r2:.3f}")

# Compare actual vs predicted monthly totals for test set
test_df = df[test_idx].copy()
test_df['Predicted_Rainfall_mm'] = y_pred_test

monthly_summary = test_df.groupby(['Year', 'Month'])[['Rainfall_mm', 'Predicted_Rainfall_mm']].sum().reset_index()
monthly_summary['Period'] = monthly_summary['Year'].astype(str) + '-' + monthly_summary['Month'].astype(str).str.zfill(2)

plt.figure(figsize=(12, 5))
plt.plot(monthly_summary['Period'], monthly_summary['Rainfall_mm'], label='Actual Rainfall (mm)', marker='o', color='royalblue')
plt.plot(monthly_summary['Period'], monthly_summary['Predicted_Rainfall_mm'], label='Predicted Rainfall (mm)', marker='s', color='darkorange', linestyle='--')
plt.xticks(rotation=45)
plt.xlabel('Year-Month')
plt.ylabel('Total Monthly Rainfall (mm)')
plt.title('Actual vs Predicted Monthly Rainfall (2023 - 2024 Test Set)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Integrate predicted rainfall with catchment parameters for harvesting
CATCHMENT_AREA_M2 = 9522.35
RUNOFF_COEFFICIENT = 0.85

test_df['Harvested_Liters_Pred'] = test_df['Predicted_Rainfall_mm'] * CATCHMENT_AREA_M2 * RUNOFF_COEFFICIENT

annual_harvest_pred = test_df.groupby('Year')['Harvested_Liters_Pred'].sum() / 1e6
print("\nPredicted Annual Rainwater Harvesting Yield (Megaliters):")
print(annual_harvest_pred)

# ==========================================================
# 1. MOUNT GOOGLE DRIVE
# ==========================================================
from google.colab import drive
import os

drive.mount('/content/drive')

# Target save directory inside Google Drive
save_dir = '/content/drive/MyDrive/Rainwater_Harvesting_Project/'
os.makedirs(save_dir, exist_ok=True)

# ==========================================================
# 2. IMPORT LIBRARIES & LOAD DATA
# ==========================================================
import numpy as np
import pandas as pd
import joblib
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('pimpri_chinchwad_rainfall_2015_2024.csv')
df['Date'] = pd.to_datetime(df['Date'])

# ==========================================================
# 3. FEATURE ENGINEERING
# ==========================================================
# Seasonal cyclical transformations
df['Sin_Month'] = np.sin(2 * np.pi * df['Month'] / 12)
df['Cos_Month'] = np.cos(2 * np.pi * df['Month'] / 12)

# Autoregressive lag and moving averages
df['Rain_Lag1'] = df['Rainfall_mm'].shift(1).fillna(0)
df['Rain_Rolling7'] = df['Rainfall_mm'].rolling(window=7, min_periods=1).mean()

features = ['Temperature_C', 'Humidity_pct', 'Sin_Month', 'Cos_Month', 'Rain_Lag1', 'Rain_Rolling7']
target = 'Rainfall_mm'

X = df[features]
y = df[target]

# Train-Test Split (2015-2022 Train, 2023-2024 Test)
train_idx = df['Year'] < 2023
test_idx = df['Year'] >= 2023

X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]

# ==========================================================
# 4. MODEL TRAINING & EVALUATION
# ==========================================================
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions (Clipped at 0 to avoid non-physical negative rainfall)
y_pred_train = np.clip(model.predict(X_train), 0, None)
y_pred_test = np.clip(model.predict(X_test), 0, None)

# Calculate performance metrics
train_mae = mean_absolute_error(y_train, y_pred_train)
train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
train_r2 = r2_score(y_train, y_pred_train)

test_mae = mean_absolute_error(y_test, y_pred_test)
test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
test_r2 = r2_score(y_test, y_pred_test)

print("=" * 45)
print("       LINEAR REGRESSION MODEL METRICS       ")
print("=" * 45)
print(f"Train R² Score : {train_r2:.4f} | Train MAE : {train_mae:.3f} mm | Train RMSE : {train_rmse:.3f} mm")
print(f"Test R² Score  : {test_r2:.4f} | Test MAE  : {test_mae:.3f} mm | Test RMSE  : {test_rmse:.3f} mm")
print("=" * 45)

# ==========================================================
# 5. EXPORT TRAINED MODEL & METADATA TO DRIVE
# ==========================================================
# 1. Save trained model object
model_path = os.path.join(save_dir, 'rainfall_linear_regressor.joblib')
joblib.dump(model, model_path)
print(f"\n[Saved Model]: {model_path}")

# 2. Save active notebook copy to Drive with the designated name
notebook_name = "Predictive Rainwater Harvesting Optimization System (linear regressor rainfall prediction).ipynb"
notebook_save_path = os.path.join(save_dir, notebook_name)

# Attempt to copy current session notebook if available in Colab environment
try:
    import shutil
    shutil.copy('/content/drive/MyDrive/Colab Notebooks/' + notebook_name, notebook_save_path)
    print(f"[Saved Notebook]: {notebook_save_path}")
except Exception:
    # Alternative direct rename/save inside standard Colab Drive directory
    print(f"\nTo ensure the notebook itself is named correctly in Drive:")
    print(f"Go to 'File' -> 'Save a copy in Drive' or rename the notebook to:\n'{notebook_name}'")